export const INIT = '@@INIT'
export const REDUX_INIT = '@@redux/INIT'

export const DASHES_LIST = 'centify/dashes/LIST'
export const DASHES_LIST_SUCCESS = 'centify/dashes/LIST_SUCCESS'
export const DASHES_LIST_FAIL = 'centify/dashes/LIST_FAIL'
export const DASHES_FILTER = 'centify/dashes/LIST_FILTER'
export const DASHES_SINGLE_GET = 'centify/dashes/SINGLE_GET'
export const DASHES_SINGLE_GET_SUCCESS = 'centify/dashes/SINGLE_GET_SUCCESS'
export const DASHES_SINGLE_GET_FAIL = 'centify/dashes/SINGLE_GET_FAIL'
export const DASHES_SINGLE_GET_PARTICIPANTS = 'centify/dashes/SINGLE_GET_PARTICIPANTS'
export const DASHES_SINGLE_GET_PARTICIPANTS_SUCCESS = 'centify/dashes/SINGLE_GET_PARTICIPANTS_SUCCESS'
export const DASHES_SINGLE_GET_PARTICIPANTS_FAIL = 'centify/dashes/SINGLE_GET_PARTICIPANTS_FAIL'
export const DASHES_SINGLE_GET_REWARDS = 'centify/dashes/SINGLE_GET_REWARDS'
export const DASHES_SINGLE_GET_REWARDS_SUCCESS = 'centify/dashes/SINGLE_GET_REWARDS_SUCCESS'
export const DASHES_SINGLE_GET_REWARDS_FAIL = 'centify/dashes/SINGLE_GET_REWARDS_FAIL'
